version: '3.8'

services:
  whatsapp-api:
    build: .
    container_name: whatsapp-web-api
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./sessions:/app/sessions
    environment:
      - PORT=3000
      - API_KEY=${API_KEY}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - SESSION_PATH=/app/sessions
    env_file:
      - .env
    security_opt:
      - seccomp=unconfined
    shm_size: '2gb'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
