services:
  whatsapp-api:
    build: .
    container_name: whatsapp-web-api
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./sessions:/app/sessions
      - ./logs:/app/logs
    environment:
      - PORT=3000
      - API_KEY=${API_KEY}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - SESSION_PATH=/app/sessions
      - MONGODB_URI=mongodb://mongodb:27017/whatsapp-api
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ALWAYS_ONLINE=${ALWAYS_ONLINE:-true}
      - LOG_DIR=/app/logs
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    security_opt:
      - seccomp=unconfined
    shm_size: '2gb'
    mem_limit: 2g
    mem_reservation: 1g
    cpus: '2.0'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - whatsapp-network

  mongodb:
    image: mongo:7.0
    container_name: whatsapp-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=whatsapp-api
    mem_limit: 1g
    mem_reservation: 512m
    networks:
      - whatsapp-network

  redis:
    image: redis:7-alpine
    container_name: whatsapp-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    mem_limit: 512m
    mem_reservation: 256m
    networks:
      - whatsapp-network

  mcp-server:
    build: ./mcp-server
    container_name: whatsapp-mcp-server
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - WHATSAPP_API_URL=http://whatsapp-api:3000
      - WHATSAPP_API_KEY=${API_KEY}
      - PORT=3001
    env_file:
      - ./mcp-server/.env
    depends_on:
      - whatsapp-api
    mem_limit: 512m
    mem_reservation: 256m
    cpus: '1.0'
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - whatsapp-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  whatsapp-network:
    driver: bridge
